name: Maven Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11  # Use the appropriate Java version

    - name: Build and Install
      run: mvn clean install -DskipTests -pl byte-buddy-dep -am

    - name: Run Tests
      run: mvn -pl byte-buddy-dep test -Dtest='net.bytebuddy.description.method.MethodDescriptionLatentTest#testExceptions'

    - name: Run NonDex Plugin
      run: mvn -pl byte-buddy-dep edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest='net.bytebuddy.description.method.MethodDescriptionLatentTest#testExceptions'
